using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ZEngine.Ecs.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ComponentGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MustBePartial = new(
        "ZEC1001",
        "Component must be partial",
        "Component '{0}' must be declared partial so schema metadata can be generated",
        "ZEngine.Ecs",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor ManagedField = new(
        "ZEC1002",
        "Unmanaged component contains managed field",
        "Component '{0}' field '{1}' has managed type '{2}'; use the explicit managed-component path",
        "ZEngine.Ecs",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NestedComponent = new(
        "ZEC1003",
        "Nested component is not supported",
        "Component '{0}' must be declared directly in a namespace",
        "ZEngine.Ecs",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> components =
            context.SyntaxProvider.ForAttributeWithMetadataName(
                "ZEngine.Ecs.ComponentAttribute",
                static (node, _) => node is StructDeclarationSyntax,
                static (attributeContext, _) =>
                    (INamedTypeSymbol)attributeContext.TargetSymbol);

        context.RegisterSourceOutput(
            components,
            static (productionContext, component) =>
                Generate(productionContext, component));
    }

    private static void Generate(
        SourceProductionContext context,
        INamedTypeSymbol component)
    {
        Location? location = component.Locations.FirstOrDefault();
        if (component.ContainingType is not null)
        {
            context.ReportDiagnostic(
                Diagnostic.Create(
                    NestedComponent,
                    location,
                    component.ToDisplayString()));
            return;
        }

        bool isPartial = component.DeclaringSyntaxReferences
            .Select(reference => reference.GetSyntax())
            .OfType<StructDeclarationSyntax>()
            .Any(declaration => declaration.Modifiers.Any(
                modifier => modifier.IsKind(SyntaxKind.PartialKeyword)));
        if (!isPartial)
        {
            context.ReportDiagnostic(
                Diagnostic.Create(
                    MustBePartial,
                    location,
                    component.ToDisplayString()));
            return;
        }

        foreach (IFieldSymbol field in component.GetMembers().OfType<IFieldSymbol>())
        {
            if (!field.IsStatic && !field.Type.IsUnmanagedType)
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        ManagedField,
                        field.Locations.FirstOrDefault() ?? location,
                        component.ToDisplayString(),
                        field.Name,
                        field.Type.ToDisplayString()));
                return;
            }
        }

        string fullyQualifiedName = component.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat);
        string stableName = component.ToDisplayString(
            SymbolDisplayFormat.CSharpErrorMessageFormat);
        ulong stableId = StableHash(stableName);
        string namespaceName = component.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : component.ContainingNamespace.ToDisplayString();
        StringBuilder source = new();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        if (namespaceName.Length > 0)
        {
            source.Append("namespace ").Append(namespaceName).AppendLine(";");
            source.AppendLine();
        }

        source.Append("partial struct ").Append(component.Name).AppendLine();
        source.AppendLine("{");
        source.AppendLine("    public static class GeneratedSchema");
        source.AppendLine("    {");
        source.Append("        public const ulong StableId = 0x")
            .Append(stableId.ToString("X16"))
            .AppendLine("UL;");
        source.Append("        public const string Name = \"")
            .Append(Escape(stableName))
            .AppendLine("\";");
        source.Append("        public static int Size => global::System.Runtime.CompilerServices.Unsafe.SizeOf<")
            .Append(fullyQualifiedName)
            .AppendLine(">();");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource(
            Sanitize(stableName) + ".Component.g.cs",
            SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static ulong StableHash(string value)
    {
        const ulong offset = 14695981039346656037;
        const ulong prime = 1099511628211;
        ulong hash = offset;
        foreach (byte valueByte in Encoding.UTF8.GetBytes(value))
        {
            hash ^= valueByte;
            hash *= prime;
        }

        return hash;
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string Sanitize(string value)
    {
        StringBuilder result = new(value.Length);
        foreach (char character in value)
        {
            result.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return result.ToString();
    }
}
