<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ZEngine.Ecs</RootNamespace>
    <AssemblyName>ZEngine.Ecs</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Foundation\ZEngine.Core\ZEngine.Core.csproj" />
    <ProjectReference Include="..\..\Jobs\ZEngine.Jobs\ZEngine.Jobs.csproj" />
  </ItemGroup>
</Project>
