<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ZEngine.Vulkan.Raw</RootNamespace>
    <AssemblyName>ZEngine.Vulkan.Raw</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Foundation\ZEngine.Core\ZEngine.Core.csproj" />
  </ItemGroup>
</Project>
