<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ZGame.Slice.Gameplay</RootNamespace>
    <AssemblyName>ZGame.Slice.Gameplay</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZGame.Slice.Contracts\ZGame.Slice.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Ecs\ZEngine.Ecs\ZEngine.Ecs.csproj" />
    <ProjectReference Include="..\..\src\Plugins\ZEngine.Plugins.Abstractions\ZEngine.Plugins.Abstractions.csproj" />
  </ItemGroup>
</Project>
