<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ZEngine.UI.Vulkan</RootNamespace>
    <AssemblyName>Zui.Backend.Vulkan</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Graphics\ZEngine.Graphics.Vulkan\ZEngine.Graphics.Vulkan.csproj" />
    <ProjectReference Include="..\Zui.Rendering\Zui.Rendering.csproj" />
  </ItemGroup>
</Project>
