<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ZGame.Slice.RenderFeature</RootNamespace>
    <AssemblyName>ZGame.Slice.RenderFeature</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZGame.Slice.Contracts\ZGame.Slice.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Graphics\ZEngine.RenderGraph\ZEngine.RenderGraph.csproj" />
    <ProjectReference Include="..\..\src\Plugins\ZEngine.Plugins.Abstractions\ZEngine.Plugins.Abstractions.csproj" />
  </ItemGroup>
</Project>
