using System.CodeDom.Compiler;

namespace ZEngine.Vulkan.Registry;

public static class VulkanRegistryCodeWriter
{
    public static void Write(
        VulkanRegistrySnapshot registry,
        TextWriter output)
    {
        ArgumentNullException.ThrowIfNull(registry);
        ArgumentNullException.ThrowIfNull(output);

        using IndentedTextWriter writer = new(output, "    ");
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("namespace ZEngine.Vulkan.Raw.Generated;");
        writer.WriteLine();
        writer.WriteLine("public static class VulkanRegistryInfo");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine(
            $"public static Version HighestCoreVersion {{ get; }} = new({registry.HighestCoreFeature.Version.Major}, {registry.HighestCoreFeature.Version.Minor});");
        writer.WriteLine($"public const int HandleCount = {registry.Handles.Count};");
        writer.WriteLine($"public const int CommandCount = {registry.Commands.Count};");
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();

        for (int index = 0; index < registry.Handles.Count; index++)
        {
            VulkanHandle handle = registry.Handles[index];
            string storageType = handle.IsDispatchable ? "nint" : "ulong";
            writer.WriteLine(
                $"public readonly record struct {handle.Name}({storageType} Value)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public bool IsNull => Value == 0;");
            writer.Indent--;
            writer.WriteLine("}");
            if (index + 1 < registry.Handles.Count)
            {
                writer.WriteLine();
            }
        }
    }
}
